### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by mferrie** [Gaiiden/RoverDriver#1]
I noticed that the script is for kOS v13.1. Please update it to the current version; I really would like to test it!

Also, please add a way to make waypoints actual LATLNG()s!

**Comment by Gaiiden** [comment]
not going to happen. The next time I need to write some rover software I will be revisiting this code but only as a framework to rebuild with all the cool new features of whatever kOS version is out at the time. I'm talking months from now, if not next year.

However I'm not aware of any major breaking changes that should affect this script. Might need a little TLC but it should still run pretty well.

**Comment by mferrie** [comment]
Ok, I'll see what I can do to get this to work in my game.
